IF DB_ID('CaroDb') IS NULL
BEGIN
    CREATE DATABASE CaroDb;
END
GO

USE CaroDb;
GO

IF OBJECT_ID('dbo.Users', 'U') IS NULL
BEGIN
CREATE TABLE dbo.Users (
  Id INT IDENTITY PRIMARY KEY,
  Username NVARCHAR(100) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(256) NOT NULL,
  DisplayName NVARCHAR(100),
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
END
GO

IF OBJECT_ID('dbo.Games', 'U') IS NULL
BEGIN
CREATE TABLE dbo.Games (
  Id INT IDENTITY PRIMARY KEY,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
  FinishedAt DATETIME2 NULL,
  Result NVARCHAR(50) NULL,
  Mode NVARCHAR(20) NOT NULL,
  P1UserId INT NULL,
  P2UserId INT NULL,
  PveDifficulty INT NULL,
  TimeControlSeconds INT NOT NULL,
  CurrentTurn INT DEFAULT 1,
  CONSTRAINT FK_Games_P1 FOREIGN KEY (P1UserId) REFERENCES dbo.Users(Id),
  CONSTRAINT FK_Games_P2 FOREIGN KEY (P2UserId) REFERENCES dbo.Users(Id)
);
END
GO

IF OBJECT_ID('dbo.Moves', 'U') IS NULL
BEGIN
CREATE TABLE dbo.Moves (
  Id INT IDENTITY PRIMARY KEY,
  GameId INT NOT NULL,
  Player INT NOT NULL,
  X INT NOT NULL,
  Y INT NOT NULL,
  MoveNumber INT NOT NULL,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Moves_Games FOREIGN KEY (GameId) REFERENCES dbo.Games(Id)
);
END
GO

IF OBJECT_ID('dbo.GameHistory', 'U') IS NULL
BEGIN
CREATE TABLE dbo.GameHistory (
  Id INT IDENTITY PRIMARY KEY,
  GameId INT NOT NULL,
  Event NVARCHAR(200) NOT NULL,
  CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_History_Games FOREIGN KEY (GameId) REFERENCES dbo.Games(Id)
);
END
GO


